import numpy as np

# PREPROCESSING PARAMETERS
tr      = 5    # "wobble length" tolerance threshold which we allow breaks to be inexact
window  = 500  # base-pairs considered to the left and right of the break TODO: this really should be chosen based on the fraglen
gl_th   = 10   # SVs considered germline if matching by at least this many bp, when comparing set of breaks to germline
support_adjust_factor = 1.25

valid_chroms    = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', \
                   '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']

# parameters extracted for each read from BAMs
read_dtype = [('query_name', 'S150'), ('chrom', 'S50'), ('ref_start', int), ('ref_end', int), \
              ('align_start', int), ('align_end', int), ('len', int), ('ins_len', int), ('is_reverse', np.bool)]

# PHYL constant parameters
subclone_diff           = 0.10 # merge any clusters within this range
clus_limit              = 25 # maximum number of clusters generated by dirichlet process
sv_offset               = 100000 # shift SV pos this far (in the SVs directionalit) to match CNV states
phi_limit               = 2

# SV classification class names
inversion_class          = ['INV']
deletion_class           = ['DEL']
dna_gain_class           = ['DUP','INTDUP']    #classes of variations where normal reads are not disturbed
dna_loss_class           = ['DEL','INV','TRX'] #classes of variations where normal reads are disturbed
itrx_class               = ['INTRX']
